Repository BAKUSOUMARU/Onhold, pull requests merged in 2022-08, with the labels that each got.

#33 prefabのscriptの調整
  Assets/3Wada/prefab/scoreitem.prefab
  Assets/3Wada/script/Enemycontroller.cs
  Assets/3Wada/script/PlayeDestroy.cs
  Assets/3Wada/script/hammercontroller.cs
  Assets/3Wada/script/scoreitem.cs
Labels: 未完了 :x:

#39 [Stage2]仮完成（何か追加したところなどあれば追加します。）
  Assets/1Ono/Assets/Stage2地面素材.asset
  Assets/1Ono/Assets/Stage2地面素材.asset.meta
  Assets/1Ono/OnoScenes.meta
  Assets/1Ono/OnoScenes/OnoSatoruScene.unity
  Assets/1Ono/OnoScenes/OnoSatoruScene.unity.meta
  Assets/1Ono/OnoScenes/OnoStageScene2.unity
  Assets/1Ono/OnoScenes/OnoStageScene2.unity.meta
  Assets/1Ono/Prehubs/Stage1Prehubs.meta
  Assets/1Ono/Prehubs/Stage1Prehubs/Grid.prefab
  Assets/1Ono/Prehubs/Stage1Prehubs/Grid.prefab.meta
  Assets/1Ono/Prehubs/Stage1Prehubs/New Palette.prefab
  Assets/1Ono/Prehubs/Stage1Prehubs/New Palette.prefab.meta
  Assets/1Ono/Prehubs/Stage1Prehubs/Square (1).prefab
  Assets/1Ono/Prehubs/Stage1Prehubs/Square (1).prefab.meta
  Assets/1Ono/Prehubs/Stage1Prehubs/Square (2).prefab
  Assets/1Ono/Prehubs/Stage1Prehubs/Square (2).prefab.meta
  Assets/1Ono/Prehubs/Stage1Prehubs/Square (3).prefab
  Assets/1Ono/Prehubs/Stage1Prehubs/Square (3).prefab.meta
  Assets/1Ono/Prehubs/Stage1Prehubs/Square (4).prefab
  Assets/1Ono/Prehubs/Stage1Prehubs/Square (4).prefab.meta
  Assets/1Ono/Prehubs/Stage1Prehubs/Square (5).prefab
  Assets/1Ono/Prehubs/Stage1Prehubs/Square (5).prefab.meta
  Assets/1Ono/Prehubs/Stage1Prehubs/Square.prefab
  Assets/1Ono/Prehubs/Stage1Prehubs/Square.prefab.meta
  Assets/1Ono/Prehubs/Stage2Palette.prefab
  Assets/1Ono/Prehubs/Stage2Palette.prefab.meta
  Assets/2Miyagi/Prefabs/Player/Player2D.prefab
  Assets/Master/Stage/Stage1.unity
Labels: 仕様 デザイン など :art:, 完了 :ballot_box_with_check:

#41 ライトの追加
  Assets/2Miyagi/2D Miyagi Scene.unity
  Assets/2Miyagi/2DScript/Enemy/EnemyController.cs
  Assets/2Miyagi/2DScript/Player/CharacterMove.cs
  Assets/2Miyagi/2DScript/shadow.mat
  Assets/2Miyagi/2DScript/shadow.mat.meta
  Assets/2Miyagi/Prefabs/Gimmick/Item/Battery.prefab
  Assets/2Miyagi/Prefabs/Gimmick/Item/Battery.prefab.meta
  Assets/2Miyagi/Prefabs/Gimmick/Item/ItemGimmick.cs
  Assets/2Miyagi/Prefabs/Player/Player2D.prefab
Labels: 完了 :ballot_box_with_check:

#42 [Stage1.2]プレイヤーのアニメーションとstageのバックグラウンド追加
  Assets/1Ono/Assets/Players.meta
  Assets/1Ono/Assets/Players/Animation.meta
  Assets/1Ono/Assets/Players/Animation/IMG_1087.controller
  Assets/1Ono/Assets/Players/Animation/IMG_1087.controller.meta
  Assets/1Ono/Assets/Players/Animation/IMG_1093.controller
  Assets/1Ono/Assets/Players/Animation/IMG_1093.controller.meta
  Assets/1Ono/Assets/Players/Animation/LeftAnimation.anim
  Assets/1Ono/Assets/Players/Animation/LeftAnimation.anim.meta
  Assets/1Ono/Assets/Players/Animation/New Animation.anim
  Assets/1Ono/Assets/Players/Animation/New Animation.anim.meta
  Assets/1Ono/Assets/Players/Animation/Player2D.controller
  Assets/1Ono/Assets/Players/Animation/Player2D.controller.meta
  Assets/1Ono/Assets/Players/Animation/RightAnimation.anim
  Assets/1Ono/Assets/Players/Animation/RightAnimation.anim.meta
  Assets/1Ono/Assets/Players/IMG_1073.png
  Assets/1Ono/Assets/Players/IMG_1073.png.meta
  Assets/1Ono/Assets/Players/IMG_1087.png
  Assets/1Ono/Assets/Players/IMG_1087.png.meta
  Assets/1Ono/Assets/Players/IMG_1088.png
  Assets/1Ono/Assets/Players/IMG_1088.png.meta
  Assets/1Ono/Assets/Players/IMG_1089.png
  Assets/1Ono/Assets/Players/IMG_1089.png.meta
  Assets/1Ono/Assets/Players/IMG_1093.png
  Assets/1Ono/Assets/Players/IMG_1093.png.meta
  Assets/1Ono/Assets/Players/IMG_1094.png
  Assets/1Ono/Assets/Players/IMG_1094.png.meta
  Assets/1Ono/Assets/Players/IMG_1095.png
  Assets/1Ono/Assets/Players/IMG_1095.png.meta
  Assets/1Ono/Assets/Stage.meta
  Assets/1Ono/Assets/Stage/Stage1BackGround.png
  Assets/1Ono/Assets/Stage/Stage1BackGround.png.meta
  Assets/1Ono/Assets/Stage/Stage2BackGround.png
  Assets/1Ono/Assets/Stage/Stage2BackGround.png.meta
  Assets/1Ono/Assets/Stage/Stage2地面素材.asset
  Assets/1Ono/Assets/Stage/Stage2地面素材.asset.meta
  Assets/1Ono/Assets/Stage/地面素材.asset
  Assets/1Ono/Assets/Stage/地面素材.asset.meta
  Assets/1Ono/Assets/Stage/地面素材.png
  Assets/1Ono/Assets/Stage/地面素材.png.meta
  Assets/1Ono/OnoScenes/OnoSatoruScene.unity
  Assets/1Ono/OnoScenes/OnoStageScene2.unity
  Assets/1Ono/Prehubs/Stage1Prehubs/Stage1BackGround.prefab
  Assets/1Ono/Prehubs/Stage1Prehubs/Stage1BackGround.prefab.meta
  Assets/1Ono/Prehubs/Stage2Prehubs.meta
  Assets/1Ono/Prehubs/Stage2Prehubs/BackGround.prefab
  Assets/1Ono/Prehubs/Stage2Prehubs/BackGround.prefab.meta
  Assets/1Ono/Prehubs/Stage2Prehubs/Stage2Grid.prefab
  Assets/1Ono/Prehubs/Stage2Prehubs/Stage2Grid.prefab.meta
  Assets/1Ono/Prehubs/Stage2Prehubs/Stage2Palette.prefab
  Assets/1Ono/Prehubs/Stage2Prehubs/Stage2Palette.prefab.meta
  Assets/2Miyagi/2DScript/Player/CharacterMove.cs
  Assets/2Miyagi/Prefabs/Player/Player2D.prefab
  Assets/Master/Stage/Stage1.unity
Labels: 仕様 デザイン など :art:
